name: rota_app
description: Applicativo ROTA - Controle de Rotas
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.3
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  flutter_riverpod: ^2.0.0
  go_router: ^6.0.0
  dio: ^5.0.0
  flutter_dotenv: ^5.0.0
  equatable: ^2.0.3
  image_picker: ^1.0.4
  file_selector: ^1.0.3
  flutter_map: ^6.1.0
  latlong2: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env_dev
    - .env_prod
    - assets/images/logo_rota.png
    - lib/
    - lib/core/
    - lib/core/routes/
    - lib/core/routes/data/
    - lib/core/helpers/
    - lib/core/network/
    - lib/shared/
    - lib/shared/themes/
    - lib/modules/
    - lib/modules/auth/
    - lib/modules/auth/data/
    - lib/modules/auth/widgets/
    - lib/modules/auth/presentation/
    - lib/modules/home/
    - lib/modules/home/presentation/
    - lib/modules/anexos/
    - lib/modules/anexos/data/
    - lib/modules/anexos/widgets/
    - lib/modules/anexos/presentation/
    - lib/modules/routes/
    - lib/modules/routes/data/
    - lib/modules/routes/domain/
    - lib/modules/routes/domain/models/
    - lib/modules/routes/widgets/
    - lib/modules/routes/presentation/
    - lib/modules/routes/presentation/widgets/
    - lib/modules/settings/
    - lib/modules/settings/presentation/
    - lib/modules/navigation/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700